UP              add volume +5; script-message-to uosc flash-elements volume
DOWN            add volume -5; script-message-to uosc flash-elements volume
ENTER           cycle fullscreen; script-binding uosc/toggle-ui
KP_ENTER        cycle fullscreen; script-binding uosc/toggle-ui
RIGHT           seek 5; script-message-to uosc flash-elements timeline
LEFT            seek -5; script-message-to uosc flash-elements timeline
CTRL+RIGHT      seek 30; script-message-to uosc flash-elements timeline
CTRL+LEFT       seek -30; script-message-to uosc flash-elements timeline
SHIFT+RIGHT     seek 60; script-message-to uosc flash-elements timeline
SHIFT+LEFT      seek -60; script-message-to uosc flash-elements timeline
ALT+RIGHT       playlist-next
ALT+LEFT        playlist-prev
TAB             script-binding uosc/flash-ui
SHIFT+TAB       script-binding uosc/toggle-ui
CTRL+TAB       script-binding uosc/toggle-ui
SPACE           cycle pause; script-binding uosc/flash-pause-indicator; script-binding uosc/toggle-ui
m               no-osd cycle mute; script-binding uosc/flash-volume
[               no-osd add speed -0.25; script-binding uosc/flash-speed
]               no-osd add speed  0.25; script-binding uosc/flash-speed
\               no-osd set speed 1; script-binding uosc/flash-speed
